repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        - id: check-yaml
        - id: end-of-file-fixer
          types: [kotlin, java, markdown]
        - id: trailing-whitespace
          types: [kotlin, java, markdown]
  - repo: https://github.com/jguttman94/pre-commit-gradle
    rev: v0.3.0
    hooks:
      - id: gradle-task
        args: ["-w", "ktlintFormat"]
      - id: gradle-task
        args: ["-w", "dokkaHtml"]
