name: Generate docs

on:
  push:
    branches:
      - gendocs

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate docs
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Overwrite docs branch with main # From https://stackoverflow.com/a/2763118
        run: |
          git pull
          git checkout docs --
          git switch main
          git merge --strategy=ours docs
          git switch docs
          git merge main

      - name: Run dokkaHtml
        run: |
          ./gradlew dokkaHtml
          ls -la
          git add docs

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Generate html" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
